# vars/main.yml

services:
  - name: pbsexporter
    image: ghcr.io/natrontech/pbs-exporter:latest
    user: "{{ common_uid }}:{{ common_gid }}"
    env_file:
      - ./pbsexporter.env
    networks:
      - monitoring
    traefik: 
      - name: pbsexporter
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 10019
    watchtower: true