# /config/workspace/homelab/roles/0host_user_management/tasks/main.yml
---
- name: User management loop
  include_tasks: user_management.yml
  loop: "{{ users }}"
  loop_control:
    loop_var: current_user
  when: users_user_create

- name: Remove users if specified
  user:
    name: "{{ item.username }}"
    state: absent
    remove: "{{ item.remove | default('no') }}"
  loop: "{{ users_remove }}"
  when: users_remove is defined and users_remove | length > 0
  become: true

- name: Remove sudoers file for removed users
  file:
    path: "/etc/sudoers.d/{{ item.username }}"
    state: absent
  loop: "{{ users_remove }}"
  when: users_remove is defined and users_remove | length > 0
  become: true

- name: Remove groups if specified
  group:
    name: "{{ item }}"
    state: absent
  loop: "{{ groups_remove }}"
  when: groups_remove is defined and groups_remove | length > 0
  become: true