# /config/workspace/homelab/playbooks/nas.yml

- hosts: nas
  roles:
    - variables
    # - 0host_user_management
    # - robertdebock.logrotate
    # - name: geerlingguy.security
    #   become: true
    # - geerlingguy.docker
    - role: 0docker_service
      vars:
        docker_service_roles:
          - traefik
          - prometheus
          # # - rclone # needed for backrest broken
          - unifi
          - uptimekuma
          - exportarrexporter
          - pbsexporter
          - wallos
          - paperless
          # # - nexterm broken
          - changedetection
          # # - watchtower broken
          - portainer
          - librespeed
          - dockge
          - adguardsync
          - certdumper
          - nodeexporter
          - alertmanager
          - grafana
          - cadvisor
          - proxmoxexporter
          # # - adguardeexporter kein bock docker image not found
          - unifiexporter
          - plausibleexporter
          - librespeedexporter
          - plexexporter
          - tautulliexporter
          - qbittorrentexporter
          # # - valetudo not needed anymore?
          - pyload
          - czkawka
          - pairdrop
          - backrest