traefik_host: 'proxy.oiba.de'
traefik_certresolver: 'oiba'

traefik_domains:
  - main: 'oiba.de'
    sans: ['oiba.de', 'nas.oiba.de', 'opn.oiba.de', 'win.oiba.de', 'home.oiba.de']
  - main: 'sauna.re'
    sans: ['sauna.re']

additional_ports: 
  #Portainer
  - target: 8000
    published: 8000
    protocol: tcp
    mode: host
  #UNIFI
  - target: 8080
    published: 8080
    protocol: tcp
    mode: host
  - target: 1900
    published: 1900
    protocol: udp
    mode: host
  - target: 3478
    published: 3478
    protocol: udp
    mode: host
  - target: 10001
    published: 10001
    protocol: udp
    mode: host
  - target: 8843
    published: 8843
    protocol: tcp
    mode: host
  - target: 6789
    published: 6789
    protocol: tcp
    mode: host
  - target: 5514
    published: 5514
    protocol: tcp
    mode: host        

all_networks:
  - traefik
  - portainer
  - paperless
  - unifi
  - monitoring
  - adguard
  - pyload
  - valetudo
  - healthcheck
  - uptimekuma
  - librespeed
  - czkawka
  - vscode


dockerproxy_allowed_ip: 172.29.13.0/24
dockerproxy_gid: 993