- name: Include all variables from the 'variables' role
  include_vars:
    dir: "{{ ansible_home }}/roles/variables/vars"

- name: Include role-specific vars
  include_vars: "{{ ansible_home }}/roles/{{ role_specific }}/vars/main.yml"

- name: Create role directory
  become: true
  file:
    path: "{{ docker_base_path }}/{{ docker_role_name }}"
    state: directory
    owner: ansible
    group: ansible
    mode: '0755'

- name: Template Docker Compose file
  template:
    src: "{{ ansible_home }}/roles/0docker_common/templates/docker_service.j2"
    dest: "{{ docker_base_path }}/{{ docker_role_name }}/docker-compose.yml"

- name: Find all templates
  find:
    paths: "{{ ansible_home }}/roles/{{ docker_role_name }}/templates"
    patterns: "*.j2"
  delegate_to: localhost
  register: template_files

- name: Separate env and config files
  set_fact:
    env_files: "{{ template_files.files | selectattr('path', 'search', '.env.j2$') | list }}"
    config_files: "{{ template_files.files | selectattr('path', 'search', '.j2$') | rejectattr('path', 'search', '.env.j2$') | list }}"

- name: Template env files
  template:
    src: "{{ item.path }}"
    dest: "{{ docker_base_path }}/{{ docker_role_name }}/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
  loop: "{{ env_files }}"
  when: env_files | length > 0

- name: Create config directory
  file:
    path: "{{ docker_base_path }}/{{ docker_role_name }}/{{ docker_service_volume | default('config') }}"
    state: directory
  when: config_files | length > 0

- name: Template config files
  template:
    src: "{{ item.path }}"
    dest: "{{ docker_base_path }}/{{ docker_role_name }}/{{ docker_service_volume | default('config') }}/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
  loop: "{{ config_files }}"
  when: config_files | length > 0