# vars/main.yml

services:
  - name: limesurvey
    image: martialblog/limesurvey:latest
    depends_on:
      - limesurvey-mariadb
    env_file:
      - ./limesurvey.env
    volumes:
      - ./data/app/uploads:/var/www/html/upload/surveys
    networks:
      - limesurvey
    traefik:
      - name: limesurvey
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 8080
    watchtower: true

  - name: limesurvey-mariadb
    image: lscr.io/linuxserver/mariadb:latest	
    env_file:
      - ../common.env
      - ./limesurvey-mariadb.env
    volumes:
      - ./data/db:/config
    networks:
      - limesurvey
    watchtower: true