# tasks/main.yml

- name: Create Docker Networks
  docker_network:
    name: "{{ item }}"
    ipam_config:
      - subnet: "{{ docker_network_base_subnet }}.{{ loop_index+1 }}.0/24"
        gateway: "{{ docker_network_base_subnet }}.{{ loop_index+1 }}.1"
  loop: "{{ docker_networks }}"
  loop_control:
    index_var: loop_index

- name: Create base directory
  become: true
  file:
    path: "{{ docker_base_path }}"
    state: directory
    owner: "{{ common_username }}"
    group: "{{ common_group }}"
    mode: "{{ default_file_permission_mode }}"

- name: Template common.env file
  template:
    src: "{{ ansible_home }}/roles/0docker_setup/templates/common.env.j2"
    dest: "{{ docker_base_path }}/common.env"