# vars/main.yml
docker_role_name: librechat

services:
  - name: librechat
    image: ghcr.io/danny-avila/librechat-dev:latest
    depends_on:
      - librechat-mongodb
      - librechat-meilisearch
    env_file:
      - ./librechat.env
    volumes:
      - ./data/images:/app/client/public/images
      - ./config:/config
      - ./data/logs:/app/api/logs
    networks:
      - librechat
    traefik:
      - name: librechat
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[services[0].name][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 3080
    watchtower: true

  - name: librechat-mongodb
    image: mongo:latest
    # command:
      # - "mongod --noauth"
    volumes:
      - ./db/db:/data/db # both needed like this
      - ./db/configdb:/data/configdb # both needed like this
    networks:
      - librechat
    watchtower: true

  - name: librechat-meilisearch
    image: getmeili/meilisearch:latest
    env_file:
      - ./librechat.env
    volumes:
      - ./data/meilisearch:/meili_data
    networks:
      - librechat
    watchtower: true
