# vars/main.yml

services:
  - name: tautulliexporter
    image: nwalke/tautulli_exporter:latest
    env_file:
      - ./tautulliexporter.env
    networks:
      - monitoring
    traefik: 
      - name: tautulliexporter
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9487
    watchtower: true