# vars/main.yml
docker_role_name: alertmanager

services:
  - name: alertmanager
    image: homelab/roles/prometheus
    user: "{{ common_uid }}:{{ common_gid }}"
    command:
    - --config.file=/config/alertmanager.yml
    - --storage.path=/data
    - --web.external-url=https://{{ alertmanager_url }}
    networks:
      - monitoring
    volumes:
      - ./config:/config
      - ./data:/data
    traefik: 
      - name: alertmanager
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: Host(`{{ alertmanager_url }}`)
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9093
    watchtower: true