# vars/main.yml

services:
  - name: openwebui
    image: ghcr.io/open-webui/open-webui:main
    env_file:
      - ./openwebui.env
    volumes:
      - ./data/openwebui:/app/backend/data
    networks:
      - librechat
    traefik:
      - name: openwebui
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']][0] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 3000
    watchtower: true

  - name: openwebui-postgres
    image: postgres:alpine
    env_file:
      - ./openwebui-postgres.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - librechat
    watchtower: true

  - name: openwebui-qdrant
    image: qdrant/qdrant:latest
    volumes:
      - ./config/qdrant-config.yaml:/qdrant/config/production.yaml
      - ./data/qdrant/storage:/qdrant/storage
      - ./data/qdrant/snapshots:/qdrant/snapshots
    networks:
      - librechat
    traefik:
      - name: openwebui-qdrant
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`qdrant.sauna.re`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 6333
    watchtower: true

  - name: openwebui-docling
    image: quay.io/docling-project/docling-serve:latest
    networks:
      - librechat
    watchtower: true

  - name: openwebui-mcpo
    image: ghcr.io/open-webui/mcpo:latest
    command: --config /config/config.json --api-key {{ OPENWEBUI_MCPO_API_KEY }}
    networks:
      - librechat
    volumes:
      - ./config/mcpo.json:/config/config.json
    traefik:
      - name: openwebui-mcpo
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']][1] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 8000
    watchtower: true