# vars/main.yml
docker_role_name: czkawka

services:
  - name: czkawka
    image: jlesage/czkawka:latest
    env_file:
      - ./czkawka.env
    volumes:
      - ./data:/config
      - /srv/dev-disk-by-uuid-4cf2cd9e-0885-47b9-ada6-6005c3daa474/Multimedia:/storage
    networks:
      - pyload
    traefik: 
      - name: czkawka
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints.czkawka[ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 5800
    watchtower: true