# vars/dmz.yml

# Package Installation
is_proxmox_vm: true
nfs_needed: true

# Swap Configuration
swap_file: /swapfile
swap_file_size_mb: 4096
swap_swappiness: 30
swap_file_state: present


# TRAEFIK
traefik_oauth_address: http://authelia:9091/api/verify?rd=https%3A%2F%2Fauth.sauna.re%2F
traefik_ca_productive: true
traefik_oauth_insecureSkipVerify: false

traefik_domains:
  - main: sauna.re
    sans:
      - "*.sauna.re"
      - "*.dmz.sauna.re"

traefik_extra_hosts:
  - host.docker.internal:172.17.0.1

traefik_extra_servers:
  - name: saunaflix_statuspage
    entrypoint: https
    middleware: public-chain@file","redirectSaunaflix@file
    url: status.sauna.re
    backend_url: https://uptime.oiba.de
    insecuretransport: false
  - name: homeassistant
    entrypoint: https
    middleware: public-chain@file
    url: home.sauna.re
    backend_url: https://home.sauna.re
    insecuretransport: false

# traefik_additional_ports:

# CERTDUMPER
certdumper_restart_containers: plex


# DOCKERPROXY_TRAEFIK
dockerproxy_allowed_ip: 172.30.1.0/24
dockerproxy_gid: 988

# WATCHTOWER
watchtower_schedule: "0 1 * * * *"
watchtower_mail_subject_praefix: "DMZ: "