# vars/main.yml

services:
  - name: ihatemoney
    image: ihatemoney/ihatemoney:latest
    env_file:
      - ./ihatemoney.env
    networks:
      - ihatemoney
    volumes:
      - ./data:/database
    traefik: 
      - name: ihatemoney
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 8000
      - name: ihatemoney_admin
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`) && PathPrefix(`/dashboard`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 8000
    watchtower: true