- name: Install common programs
  apt:
    name: "{{ item }}"
    state: present
  loop: "{{ base_packages }}"
  register: result

- name: Install qemu-guest-agent
  apt:
    name: qemu-guest-agent
    state: present
  when: is_proxmox_vm|bool

- name: Install NFS Tools
  apt:
    name: nfs-common
    state: present
  when: nfs_needed|bool