# vars/main.yml
docker_role_name: proxmoxexporter

services:
  - name: proxmoxexporter
    image: prompve/prometheus-pve-exporter:latest
    env_file:
      - ./proxmoxexporter.env
    networks:
      - monitoring
    traefik: 
      - name: proxmoxexporter
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ proxmoxexporter_url }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9221
    watchtower: true