# vars/main.yml

services:
  - name: proxmoxexporter
    image: prompve/prometheus-pve-exporter:latest
    env_file:
      - ./proxmoxexporter.env
    networks:
      - monitoring
    traefik: 
      - name: proxmoxexporter
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9221
    watchtower: true