# vars/main.yml

services:
  - name: certdumper
    image: ghcr.io/kereis/traefik-certs-dumper:alpine
    command: "{{ '--restart-containers ' + certdumper_restart_containers if certdumper_restart_containers | default('') != '' else '' }}"
    network_mode: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik/data:/traefik:ro
      - ./ssl:/output:rw
      - ./config/plex.sh:/hook/hook.sh:ro
    watchtower: true