# vars/main.yml

services:
  - name: certdumper
    image: humenius/traefik-certs-dumper:latest
    command: "{{ '--restart-containers ' + certdumper_restart_containers if certdumper_restart_containers | default('') != '' else '' }}"
    network_mode: none
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ../traefik/data:/traefik:ro
      - ./ssl:/output:rw
    watchtower: true