---
- name: Create base directory
  become: true
  file:
    path: "{{ docker_base_path }}"
    state: directory
    owner: "{{ common_uid }}"
    group: "{{ common_gid }}"
    mode: "{{ default_file_permission_mode }}"

- name: Template common.env file
  become: true
  template:
    src: "common.env.j2"
    dest: "{{ docker_base_path }}/common.env"