# /config/workspace/homelab/roles/0docker_service/tasks/docker_service_creation.yml

- name: "[{{ role_specific }}] Include role-specific vars"
  include_vars: "{{ ansible_home }}/roles/{{ role_specific }}/vars/main.yml"

- name: "[{{ role_specific }}] Create role directory"
  become: true
  file:
    path: "{{ docker_base_path }}/{{ docker_role_name }}"
    state: directory
    owner: "{{ common_username }}"
    group: "{{ common_group_gid }}"
    mode: "{{ default_file_permission_mode }}"

- name: "[{{ role_specific }}] Template Docker Compose file"
  template:
    src: "{{ ansible_home }}/roles/0docker_service/templates/docker_service.j2"
    dest: "{{ docker_base_path }}/{{ docker_role_name }}/docker-compose.yml"
    owner: "{{ common_username }}"
    group: "{{ common_group_gid }}"
    mode: "{{ default_file_permission_mode }}"

- name: "[{{ role_specific }}] Find all templates"
  find:
    paths: "{{ ansible_home }}/roles/{{ docker_role_name }}/templates"
    patterns: "*.j2"
  delegate_to: localhost
  register: template_files

- name: "[{{ role_specific }}] Separate env and config files"
  set_fact:
    env_files: "{{ template_files.files | selectattr('path', 'search', '.env.j2$') | list }}"
    config_files: "{{ template_files.files | selectattr('path', 'search', '.j2$') | rejectattr('path', 'search', '.env.j2$') | list }}"

- name: "[{{ role_specific }}] Template env files"
  template:
    src: "{{ item.path }}"
    dest: "{{ docker_base_path }}/{{ docker_role_name }}/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ common_username }}"
    group: "{{ common_group_gid }}"
    mode: "{{ default_file_permission_mode }}"
  loop: "{{ env_files }}"
  when: env_files | length > 0

- name: "[{{ role_specific }}] Create config directory"
  file:
    path: "{{ docker_base_path }}/{{ docker_role_name }}/{{ docker_service_volume | default('config') }}"
    state: directory
    owner: "{{ common_username }}"
    group: "{{ common_group_gid }}"
    mode: "{{ default_file_permission_mode }}"
  when: config_files | length > 0

- name: "[{{ role_specific }}] Template config files"
  template:
    src: "{{ item.path }}"
    dest: "{{ docker_base_path }}/{{ docker_role_name }}/{{ docker_service_volume | default('config') }}/{{ item.path | basename | regex_replace('\\.j2$', '') }}"
    owner: "{{ common_username }}"
    group: "{{ common_group_gid }}"
    mode: "{{ default_file_permission_mode }}"
  loop: "{{ config_files }}"
  when: config_files | length > 0