# /config/workspace/homelab/roles/0docker_service/tasks/main.yml

- name: "Include role-specific tasks"
  include_tasks: "{{ ansible_home }}/roles/{{ item }}/tasks/main.yml"
  loop: "{{ docker_service_roles }}"

- name: "Include all variables from the 'variables' role"
  include_vars:
    dir: "{{ ansible_home }}/roles/variables/vars"

- name: "Iterate over docker_service_roles"
  include_tasks: docker_service_creation.yml
  vars:
    role_specific: "{{ item }}"
  loop: "{{ docker_service_roles }}"
  loop_control:
    label: "{{ item }}"