# vars/main.yml

# Default ports
traefik_default_ports:
  - target: 80
    published: 80
    protocol: tcp
    mode: host
  - target: 443
    published: 443
    protocol: tcp
    mode: host
  - target: 443
    published: 443
    protocol: udp
    mode: host

services:
  - name: traefik
    image: traefik:latest
    command:
      - --configFile=/config/traefik.yml
    depends_on:
      - dockerproxy
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    user: "{{ common_uid }}:{{ common_gid }}"
    cpus: 0.75
    env_file:
      - ../common.env
      - ./traefik.env
    ports: "{{ traefik_default_ports + (traefik_additional_ports | default([])) }}"
    networks: "{{ docker_networks }}"
    traefik_extra_hosts: "{{ traefik_extra_hosts }}"
    volumes:
      - ./config:/config:ro
      - ./data:/data
    traefik: 
      - name: traefik
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service: api@internal
      - name: traefik_prom
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`) && Path(`/metrics`)"
        middlewares: private-chain@file
        insecuretransport: false
        service: prometheus@internal
    watchtower: true
    traefik_domains: "{{ traefik_domains }}"

  - name: dockerproxy
    image: wollomatic/socket-proxy:1
    command:
      - "--allowfrom={{ dockerproxy_allowed_ip }}"
      - --listenip=0.0.0.0
      - --allowGET=/v1\..{1,2}/(version|containers/.*|events.*)
      - --shutdowngracetime=5
    read_only: true
    cap_drop:
      - ALL
    user: "65534:{{ dockerproxy_gid }}"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    watchtower: true