# vars/main.yml

docker_role_name: traefik
rename_files:
  - src: config.yml
    dest: traefik.yml

# Default ports
traefik_default_ports:
  - target: 80
    published: 80
    protocol: tcp
    mode: host
  - target: 443
    published: 443
    protocol: tcp
    mode: host
  - target: 443
    published: 443
    protocol: udp
    mode: host

services:
  - name: traefik
    image: traefik:latest
    command:
      - --configFile=/config/traefik.yml
    depends_on:
      - dockerproxy
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
    user: "{{ docker_common_puid }}:{{ docker_common_pgid }}"
    cpus: 0.75
    env_file:
      - ../common.env
      - ./traefik.env
    ports: "{{ traefik_default_ports + traefik_additional_ports }}"
    networks: "{{ docker_networks }}"
    volumes:
      - ./config:/config:ro
      - ./data:/data
    traefik: 
      - name: traefik
        network: traefik
        rule: Host(`{{ traefik_host }}`)
        https_redirection: true
        middlewares: private-chain@file
        service: api@internal
      - name: traefik-prom
        network: traefik
        rule: Host(`{{ traefik_host }}`) && Path(`/metrics`)
        https_redirection: true
        middlewares: private-chain@file
        service: prometheus@internal
    watchtower: true
    labels: "{{ traefik_domains }}"

  - name: dockerproxy
    image: wollomatic/socket-proxy:1
    command:
      - "--allowfrom={{ dockerproxy_allowed_ip }}"
      - --listenip=0.0.0.0
      - --allowGET=/v1\\..{1,2}/(version|containers/.*|events.*)
      - --shutdowngracetime=5
    read_only: true
    cap_drop:
      - ALL
    user: "65534:{{ dockerproxy_gid }}"
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    watchtower: true