---
- name: Create base directory
  become: true
  file:
    path: "{{ docker_base_path }}"
    state: directory
    owner: "{{ common_uid }}"
    group: "{{ common_gid }}"
    mode: "{{ default_file_permission_mode }}"

- name: Template common.env file
  become: true
  template:
    src: "common.env.j2"
    dest: "{{ docker_base_path }}/common.env"

- name: Check existing role directories
  become: true
  find:
    paths: "{{ docker_base_path }}"
    file_type: directory
  register: existing_directories

- name: Set facts for directory management
  set_fact:
    existing_role_dirs: "{{ existing_directories.files | map(attribute='path') | map('basename') | list }}"
    missing_role_dirs: "{{ docker_service_roles | difference(existing_directories.files | map(attribute='path') | map('basename') | list) }}"

- name: Create missing role directories
  file:
    path: "{{ docker_base_path }}/{{ item }}"
    state: directory
    owner: "{{ common_uid }}"
    group: "{{ common_gid }}"
    mode: "{{ default_file_permission_mode }}"
  become: true
  loop: "{{ missing_role_dirs }}"
  loop_control:
    label: "Creating missing directory for role {{ item }}"
  when: missing_role_dirs | length > 0