# vars/main.yml

services:
  - name: adguardsync
    image: lscr.io/linuxserver/adguardhome-sync:latest
    env_file:
      - ../common.env
    networks:
      - adguardsync
    volumes:
      - ./config:/config
    watchtower: true