# vars/main.yml

services:
  - name: changedetection
    image: lscr.io/linuxserver/changedetection.io:latest
    env_file:
      - ../common.env
      - ./changedetection.env
    volumes:
      - ./data:/datastore
    networks:
      - changedetection
    traefik: 
      - name: changedetection
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 5000
    watchtower: true
  - name: changedetection_playwright
    image: browserless/chrome:latest
    networks:
      - changedetection
    watchtower: true