# vars/main.yml
docker_role_name: plexexporter

services:
  - name: plexexporter1
    image: ghcr.io/axsuul/plex-media-server-exporter:latest
    env_file:
      - ./plexexporter.env
    networks:
      - monitoring
    traefik: 
      - name: plexexporter1
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ plexexporter1_url }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9594
  - name: plexexporter2
    image: ghcr.io/jsclayton/prometheus-plex-exporter:latest
    env_file:
      - ./plexexporter.env
    networks:
      - monitoring
    traefik: 
      - name: plexexporter2
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ plexexporter2_url }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9594
  - name: plexexporter3
    image: fabsau/plexexporter:latest
    env_file:
      - ./plexexporter.env
    networks:
      - monitoring
    traefik: 
      - name: plexexporter3
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ plexexporter3_url }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9594
    watchtower: true