# vars/main.yml
docker_role_name: adguardexporter

services:
  - name: adguardexporter
    image: ebrianne/adguard-exporter:latest
    env_file:
      - ./adguardexporter.env
    networks:
      - monitoring
    traefik: 
      - name: adguardexporter
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints.adguardexporter[ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9617
    watchtower: true