# vars/main.yml

services:
  - name: filebrowser
    image: filebrowser/filebrowser:latest
    volumes:
      - ./config/config.json:/filebrowser.json
      - ./db/database.db:/database.db
      - /filebrowser:/srv
      - /docker:/srv/docker
      - /0/merged:/srv/0/merged:rshared
      - /scripts:/srv/scripts
    networks:
      - filebrowser
    traefik:
      - name: filebrowser
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 80
    watchtower: true