# vars/main.yml

services:
  - name: librechat
    image: ghcr.io/danny-avila/librechat:latest
    user: 1000:1000
    depends_on:
      - librechat-mongodb
      - librechat-meilisearch
      - librechat-rag_api
    env_file:
      - ./librechat.env
      - ./librechat-rag_api.env
    volumes:
      - ./config:/config
      - ./data/images:/app/client/public/images
      - ./data/logs:/app/api/logs
    networks:
      - librechat
    traefik:
      - name: librechat
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 3080
    watchtower: true

  - name: librechat-mongodb
    image: mongo:latest
    # command:
      # - "mongod --noauth"
    volumes:
      - ./db/db:/data/db # both needed like this
      - ./db/configdb:/data/configdb # both needed like this
    networks:
      - librechat
    watchtower: true

  - name: librechat-meilisearch
    image: getmeili/meilisearch:v1.6.2
    env_file:
      - ./librechat-meilisearch.env
    volumes:
      - ./data/meilisearch:/meili_data
    networks:
      - librechat
    watchtower: true

  - name: librechat-rag_api
    image: ghcr.io/danny-avila/librechat-rag-api-dev-lite:latest
    depends_on:
      - librechat-vectordb
    env_file:
      - ./librechat-rag_api.env
    networks:
      - librechat
    watchtower: true

  - name: librechat-vectordb
    image: ankane/pgvector:latest
    env_file:
      - ./librechat-postgres.env
    volumes:
      - ./data/vectordb:/var/lib/postgresql/data
    networks:
      - librechat
    watchtower: true


config_files_settings:
  role_owner: 1000
  role_group: 1000
  role_folder_permission_mode: '0700'
  role_file_permission_mode: '0700'