# vars/main.yml

services:
  - name: donetick
    image: donetick/donetick:latest
    env_file:
      - ./donetick.env
    networks:
      - donetick
    volumes:
      - ./data:/donetick-data
      - ./config:/config
    traefik: 
      - name: donetick
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 2021
    watchtower: true