# vars/main.yml
services:
  - name: dockersocketproxy
    image: tecnativa/docker-socket-proxy:latest
    env_file:
      - ./dockersocketproxy.env
    ports:
      - "{{ hostvars[inventory_hostname].ansible_host }}:2375:2375"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - dockersocketproxy
    watchtower: true