# vars/main.yml
docker_role_name: inputforms

services:
  - name: inputforms
    image: ghcr.io/deck9/input:main
    depends_on:
      - inputforms-mariadb
    env_file:
      - ./inputforms.env
    volumes:
      - ./data/app:/var/www/html/storage
    networks:
      - inputforms
    traefik:
      - name: inputforms
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[services[0].name][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 8080
    watchtower: true

  - name: inputforms-mariadb
    image: linuxserver/mariadb:amd64-latest	
    env_file:
      - ../common.env
      - ./inputforms-mariadb.env
    volumes:
      - ./data/db:/config
    networks:
      - inputforms
    watchtower: true