# vars/main.yml

services:
  - name: torrent
    image: rogerfar/rdtclient:latest
    cpus: 1
    env_file:
      - ../common.env
    network_mode: host
    volumes:
      - ./data:/data/db
      - /0/merged:/0:rshared
    traefik: 
      - name: torrent
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 6500
    watchtower: true