# vars/main.yml
docker_role_name: unifiexporter

services:
  - name: unifiexporter
    image: golift/unifi-poller:latest
    env_file:
      - ./unifiexporter.env
    networks:
      - monitoring
    traefik: 
      - name: unifiexporter
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[docker_role_name][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9130
    watchtower: true