# vars/main.yml

services:
  - name: photoprism
    image: photoprism/photoprism:latest
    depends_on:
      - photoprism-mariadb
    env_file:
      - ./photoprism.env
    volumes:
      - /nfs/pictures:/config
    networks:
      - photoprism
    traefik:
      - name: photoprism
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 2342
    watchtower: true

  - name: photoprism-mariadb
    image: lscr.io/linuxserver/mariadb:latest	
    env_file:
      - ../common.env
      - ./photoprism-mariadb.env
    volumes:
      - ./data/db:/config
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 10
    networks:
      - photoprism
    watchtower: true