# vars/dmz.yml
docker_networks:
  - traefik
  - mediaserver
  - portainer
  - watchtower
  - librespeed
  - monitoring
  - dockersocketproxy
  - adguard
  - dockge
  - xteve
  - urbackup

# TRAEFIK
traefik_oauth_address: https://auth.sauna.re/api/verify
traefik_ca_productive: true
traefik_oauth_insecureSkipVerify: false

traefik_domains:
  - main: sauna.re
    sans:
      - "*.sauna.re"
      - "*.blue.sauna.re"

traefik_extra_hosts:
  - host.docker.internal:172.17.0.1

certdumper_restart_containers: plex,adguard
  
traefik_extra_servers:
  - name: saunaflix_statuspage
    entrypoint: https
    middleware: public-chain@file","redirectSaunaflix@file
    url: status.sauna.re
    backend_url: https://uptime.oiba.de
    insecuretransport: false
  - name: homeassistant
    entrypoint: https
    middleware: public-chain@file
    url: home.sauna.re
    backend_url: https://home.sauna.re
    insecuretransport: false

traefik_additional_ports:
  - name: adguard-dot
    target: 853
    published: 853
    protocol: tcp
    mode: host


# DOCKERPROXY_TRAEFIK
dockerproxy_allowed_ip: 172.30.1.0/24
dockerproxy_gid: 999

# WATCHTOWER
watchtower_schedule: "0 1 * * * *"
watchtower_mail_subject_praefix: "BLUE: "