# Host Settings
host_timezone: Europe/Berlin
docker_base_path: /docker2
docker_network_base_subnet: "172.30"
default_file_permission_mode: "770"
security_ssh_permit_root_login: "yes" # TODO REMOVE!
# Base Packages to install
base_packages:
  - ncdu
  - htop
  - nload
  - iotop
  - nano
  - cron
  - git
  - net-tools
  - dnsutils
  - iputils-ping
  - curl

# NFS Settings
nfs_mounts:
  - nfs_server: 192.168.100.3
    nfs_path: /Multimedia_Pictures
    mount_point: /nfs/pictures
    options: auto,nofail,noatime,nolock,intr,tcp,actimeo=1800

# Ansible Settings
ansible_home: "/config/workspace/homelab"
ansible_username: ansible
ansible_uid: "1000"
ansible_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDTyxApASDloZwHr0clLERRnBkalpRDO5FYVqsW2EBT6DlXH4btXbAgubnhEiY5YOp9GhI9qv+vRfUBoAx84qt9k8W1xTV7p2pg/HWKYm3V0edGt26BiLsRYLgbo3VUpdwVsKYTeJSShYkfOLUB0w5mYE+ZsWH47BUhGbe3Gyz+/aBETRPnS6iPBUDXlX1B41l54EtnPB4YLqkEi3wMigPdgU2oirwotPl/udJOf3hPxzEMPxc6Hf+iNN4ZkQXu+KyGKy7mjM6uSEvTChMxPzJgiZfLdU3/i0XvqYp0CL03ngwi2PHIKe/fswLIzQvyB258N52RaNt0waxIwKLgn63dXgGXgyw9yM9LhyOeDjVPWAjrQeq9g47WwClH4heTfpJkvOVcOArbqHbVR4KUuq/9dqFLZxELHcD+xvQab92y1ieZyhf5aeBQ9epggkzjAaCQNw8sms/6KK82CWR/yZngzAKkuSkch0VDv0ZHdCDiet9q+WPSVCVXkNN1xhzsnVM= ansible

# Fabio Settings
fabio_username: fabio
fabio_uid: "500"
fabio_authorized_keys:
  - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICEgae2MlRld7wI2e9UuDb/AX0NEiH5jRc86D3mX1EgU fabio

# Common ABC User Settings
common_username: abc
common_uid: "2000"
common_gid: "2000"
common_group: "abc"
common_group_gid: "2000"

# Admin Group
admin_group: admin
admin_gid: "1000"

# User Creation Settings
users_user_create: true
users_home_create: true
users_home: /home
users_home_mode: 700
users_shell: "/bin/bash"
users_authorized_keys_exclusive: true

# Creation of Users
users:
  - username: "{{ ansible_username }}"
    password: "{{ USER_ANSIBLE_PW }}"
    state: present
    primary_group: "{{ admin_group }}"
    groups:
      - "{{ admin_group }}"
      - docker
    uid: "{{ ansible_uid }}"
    expires: -1
    sudoer: yes
    authorized_keys: "{{ ansible_authorized_keys }}"
    lock: no
  - username: "{{ fabio_username }}"
    password: "{{ USER_FABIO_PW }}"
    state: present
    primary_group: "{{ admin_group }}"
    groups:
      - "{{ admin_group }}"
      - docker
    uid: "{{ fabio_uid }}"
    expires: -1
    sudoer: yes
    authorized_keys: "{{ fabio_authorized_keys }}"
    lock: no
  - username: "{{ common_username }}"
    password: "{{ USER_COMMON_PW }}"
    state: present
    primary_group: "{{ common_group }}"
    groups:
      - "{{ common_group }}"
    uid: "{{ common_uid }}"
    expires: -1
    sudoer: no
    authorized_keys: []
    lock: no

# Group Creation and User Assignment
group_management:
  - name: "{{ admin_group }}"
    gid: "{{ admin_gid }}"
    users: 
      - "root"
  - name: "{{ common_group }}"
    gid: "{{ common_group_gid }}"
    users:
      - root
      - "{{ ansible_username }}"
      - "{{ fabio_username }}"

# Removal of Users and Groups
users_remove: []
groups_remove: []

security_ssh_allowed_groups:
  - "{{ admin_group }}"
security_ssh_allowed_users:
  - "{{ ansible_username }}"
  - "{{ fabio_username }}"
  - root # TODO REMOVE!

fail2ban_bantime: 600
fail2ban_findtime: 600
fail2ban_maxretry: 5

# Logrotate Settings
logrotate_user: "{{ common_username }}"
logrotate_group: "{{ common_group }}"
logrotate_frequency: weekly
logrotate_keep: 14
logrotate_compress: yes
logrotate_entries:
  - name: traefik_access_log
    path: "{{ docker_base_path }}/traefik/data/log/access.log"
  - name: traefik_app_log
    path: "{{ docker_base_path }}/traefik/data/log/traefik.log"

# DNS Servers
dns_servers:
  - 192.168.100.20
  - 192.168.100.21

# Adguard Sync Settings
adguardsync_schedule: "*/2 * * * *"
adguardsync_user: admin
adguardsync_password: "{{ ADGUARD_PW }}"
adguardsync_master_url: "dns.oiba.de"
adguardsync_slaves:
  - "https://dns2.oiba.de/"
  - "https://dns.azure.sauna.re"
  - "https://dns.blue.sauna.re"

# Central URLs TODO
plausible_url: data.sauna.re
plex_url: watch.sauna.re
tulli_url: tulli.sauna.re
qbittorrent_url: torrent.sauna.re
sonarr_url: sonarr.sauna.re
radarr_url: radarr.sauna.re
bazarr_url: bazarr.sauna.re
prowlarr_url: prowlarr.sauna.re
sabnzbd_url: usenet.sauna.re
homeassistant_url: home.sauna.re
uptimekuma_saunaflix_url: status.sauna.re

# Prometheus Settings
prometheus_global:
  scrape_interval: '1m'
  scrape_timeout: "1m"
prometheus_alert_rules_files:
  - "alerts.yml"

# Endpoints
endpoints:
  traefik:
    nas: "proxy.oiba.de"
    dmz: "proxy.azure.sauna.re"
    blue: "proxy.blue.sauna.re"
    prometheus_exporter: true
  watchtower:
    nas: "watchtower.oiba.de"
    dmz: "watchtower.azure.sauna.re"
    blue: "watchtower.blue.sauna.re"
    prometheus_exporter: true
    prometheus_settings:
      metrics_path: "/v1/metrics"
      bearer_token: "{{ WATCHTOWER_HTTP_API_TOKEN }}"
  prometheus:
    nas: "prom.oiba.de"
    dmz: "prom.sauna.re"
    prometheus_exporter: true
  nodeexporter:
    nas: "node.nas.oiba.de"
    dmz: "node.azure.sauna.re"
    blue: "node.blue.sauna.re"
    opn: "node.opn.oiba.de"
    home: "node.home.oiba.de"
    prometheus_exporter: true
  alertmanager:
    nas: "alert.oiba.de"
    prometheus_exporter: false
  librespeed:
    nas: "speed.nas.oiba.de"
    dmz: "speed.azure.sauna.re"
    blue: "speed.blue.sauna.re"
    prometheus_exporter: false
  portainer:
    nas: "docker.oiba.de"
    prometheus_exporter: false
  unifi:
    nas: "unifi.oiba.de"
    prometheus_exporter: false
  grafana:
    nas: "grafana.oiba.de"
    prometheus_exporter: false
  cadvisor:
    nas: "cadvisor.nas.oiba.de"
    dmz: "cadvisor.azure.sauna.re"
    blue: "cadvisor.blue.sauna.re"
    prometheus_exporter: true
  proxmoxexporter:
    nas: "proxmoxexporter.oiba.de"
    target_replacement_url:
      - "vm.oiba.de:443"
    prometheus_exporter: true
    prometheus_settings:
      metrics_path: "/pve"
      params:
        module: "default"
        cluster: "1"
        node: "1"
      relabel_configs:
        - replacement: proxmoxexporter.oiba.de
  adguardexporter:
    nas: "adguardexporter.oiba.de"
    prometheus_exporter: true
  unifiexporter:
    nas: "unifiexporter.oiba.de"
    prometheus_exporter: true
  plausibleexporter:
    nas: "plausibleexporter.oiba.de"
    prometheus_exporter: true
  valetudo:
    nas: "valetudo.oiba.de"
    prometheus_exporter: false
  pyload:
    nas: "pyload.oiba.de"
    prometheus_exporter: false
  uptimekuma:
    nas: "uptime.oiba.de"
    prometheus_exporter: true
    prometheus_settings:
      basic_auth:
        username: "admin"
        password: "{{ PROMETHEUS_UPTIMEKUMA_PASSWORD }}"
  czkawka:
    nas: "files.oiba.de"
    prometheus_exporter: false
  vscode:
    nas: "code.oiba.de"
    prometheus_exporter: false
  plexexporter:
    nas:
      - "plexexporter.oiba.de"
      - "plexexporter2.oiba.de"
      - "plexexporter3.oiba.de"
    prometheus_exporter: true
  tautulliexporter:
    nas: "tautulliexporter.oiba.de"
    prometheus_exporter: true
  qbittorrentexporter:
    nas: "qbittorrentexporter.oiba.de"
    prometheus_exporter: true
  sonarrexporter:
    nas: "sonarrexporter.oiba.de"
    prometheus_exporter: true
  radarrexporter:
    nas: "radarrexporter.oiba.de"
    prometheus_exporter: true
  sabnzbdexporter:
    nas: "sabnzbdexporter.oiba.de"
    prometheus_exporter: true
  bazarrexporter:
    nas: "bazarrexporter.oiba.de"
    prometheus_exporter: false
  prowlarrrexporter:
    nas: "prowlarrexporter.oiba.de"
    prometheus_exporter: true
  librespeedexporter:
    nas: "librespeedexporter.oiba.de"
    prometheus_exporter: true
    prometheus_settings:
      scrape_interval: "6h"
      scrape_timeout: "10m"
      metrics_path: "/probe"
      params:
        script: "librespeed"
  codeserver:
    nas: "code.oiba.de"
    prometheus_exporter: false