ansible_home: "/config/workspace/homelab"
ansible_username: ansible
ansible_group: ansible
ansible_user_pw: "{{ USER_ANSIBLE_PW }}"
ansible_uid: 1000
ansible_gid: 1000
ansible_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDc6CB3E+pb/QkdPzOwquq+ITHJ/lG4hkkIp6dbWx/fSiQsskcQdFIPUxbHRXB9imsqeUW9G+ckhO6agTgFusxAeRIp8DHwz44g2+kee+QwuZ/9q66FFWMwvjKJRlq5lWa6vQ9zEAQfPh4tAYXsiVgUo/bcaRWpGZkzByUQC+1qqX6VP70P/BbM60Kx7Fpev4U7FrkyOgwfztnC9bYZR7rPYRhNluLjXoKmXJAlyLgy3d3u4+gmGDQZZQIN+J9cvS8B2Z78hV1tijkljZzGZCZW4zd9rH6uwWACnTU= ansible

host_timezone: Europe/Berlin

docker_base_path: /docker2
docker_common_timezone: Europe/Berlin
docker_common_puid: 2000
docker_common_pgid: 2000
docker_network_base_subnet: "172.30"

docker_users:
  - root
  - "{{ ansible_username }}"

logrotate_user: "{{ ansible_username }}"
logrotate_group: "{{ ansible_group }}"
logrotate_frequency: weekly
logrotate_keep: 14
logrotate_compress: yes
logrotate_entries:
  - name: traefik_access_log
    path: "{{ docker_base_path }}/traefik/data/log/access.log"
  - name: traefik_app_log
    path: "{{ docker_base_path }}/traefik/data/log/traefik.log"