# vars/nas.yml
is_proxmox_vm: true

nfs_needed: true

security_ssh_port: 22
security_autoupdate_reboot: "true"
security_autoupdate_reboot_time: "03:00"
docker_networks:
  - traefik
  - uptimekuma
  - monitoring
  - portainer
  - paperless
  - unifi
  - adguard
  - pyload
  - valetudo
  - healthcheck
  - librespeed
  - czkawka
  - vscode
  - dockge
  - watchtower
  - adguardsync

# TRAEFIK
traefik_oauth_address: https://auth.sauna.re/api/verify
traefik_ca_productive: true
traefik_oauth_insecureSkipVerify: false
traefik_additional_ports: 
  #Portainer
  - target: 8000
    published: 8000
    protocol: tcp
    mode: host
  #UNIFI
  - target: 8081
    published: 8080
    protocol: tcp
    mode: host
  - target: 1900
    published: 1900
    protocol: udp
    mode: host
  - target: 3478
    published: 3478
    protocol: udp
    mode: host
  - target: 10001
    published: 10001
    protocol: udp
    mode: host
  - target: 6789
    published: 6789
    protocol: tcp
    mode: host
  - target: 5514
    published: 5514
    protocol: tcp
    mode: host
traefik_domains:
  - main: oiba.de
    sans:
      - "*.oiba.de"
      - "*.nas.oiba.de"
      - "*.opn.oiba.de"
      - "*.win.oiba.de"
      - "*.home.oiba.de"
  - main: sauna.re
    sans:
      - "*.sauna.re"
      
traefik_entrypoints:
  - name: portainer
    address: ":8000"
  - name: unifi
    address: ":1900/udp"
  - name: unifi2
    address: ":3478/udp"
  - name: unifi3
    address: ":5514"
  - name: unifi4
    address: ":6789"
  - name: unifi5
    address: ":8080"
  - name: unifi6
    address: ":10001/udp"
traefik_whitelist_ips:
  - 46.223.56.204
  - 172.187.202.93
  - 172.31.0.0/12
  - 192.168.251.0/24
  - 192.168.50.0/24
  - 192.168.100.0/24
  - 195.90.219.248
traefik_extra_servers:
  - name: proxmox
    entrypoint: https
    middleware: private-chain@file
    url: vm.oiba.de
    backend_url: https://192.168.100.2:8006/
    insecuretransport: true
  - name: nas
    entrypoint: https
    middleware: private-chain@file
    url: nas.oiba.de
    backend_url: http://192.168.100.3:9090/
    insecuretransport: false
  - name: opnsense
    entrypoint: https
    middleware: private-chain@file
    url: router.oiba.de
    backend_url: https://192.168.100.1/
    insecuretransport: true
  - name: opnsense_prom
    entrypoint: https
    middleware: private-chain@file
    url: node.opn.oiba.de
    backend_url: http://192.168.100.1:9100
    insecuretransport: false
  - name: home_prom
    entrypoint: https
    middleware: private-chain@file
    url: node.home.oiba.de
    backend_url: http://192.168.150.2:9100
    insecuretransport: false
  - name: adguard
    entrypoint: https
    middleware: private-chain@file
    url: dns.oiba.de
    backend_url: http://192.168.100.20:80
    insecuretransport: false
  - name: adguard2
    entrypoint: https
    middleware: private-chain@file
    url: dns2.oiba.de
    backend_url: http://192.168.100.21:80
    insecuretransport: false
  - name: switch
    entrypoint: https
    middleware: private-chain@file
    url: switch.oiba.de
    insecuretransport: true
    backend_url: https://192.168.100.11/
  - name: vacuum
    entrypoint: https
    middleware: private-chain@file
    url: vacuum.oiba.de
    backend_url: http://192.168.150.9/
    insecuretransport: false
  - name: fritzbox
    entrypoint: https
    middleware: private-chain@file
    url: fritz.oiba.de
    backend_url: https://192.168.178.1/
    insecuretransport: true
  - name: proxbak
    entrypoint: https
    middleware: private-chain@file
    url: bak.oiba.de
    backend_url: https://192.168.100.4:8007/
    insecuretransport: true

# DOCKERPROXY_TRAEFIK
dockerproxy_allowed_ip: 172.30.1.0/24
dockerproxy_gid: 993

# WATCHTOWER
watchtower_schedule: "0 0 * * * *"
watchtower_url: watchtower.oiba.de
watchtower_mail_subject_praefix: "NAS: "

# CERTDUMPER
# certdumper_restart_containers: empty

# URLs:
traefik_url: proxy.oiba.de
prometheus_url: prom.oiba.de
prometheus_monitor_name: Mozart
nodeexporter_url: node.nas.oiba.de
alertmanager_url: alert.oiba.de
librespeed_url: speed.oiba.de
portainer_url: docker.oiba.de
unifi_url: unifi.oiba.de
grafana_url: grafana.oiba.de
cadvisor_url: cadvisor.nas.oiba.de