# vars/main.yml

services:
  - name: wizarr
    image: ghcr.io/wizarrrr/wizarr:latest
    env_file:
      - ../common.env
    networks:
      - wizarr
    volumes:
      - ./data:/data/database
    traefik:
      - name: wizarr
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 5690
    watchtower: true