# vars/main.yml

services:
  - name: qbittorrentexporter
    image: ghcr.io/esanchezm/prometheus-qbittorrent-exporter:latest
    env_file:
      - ./qbittorrentexporter.env
    networks:
      - monitoring
    traefik: 
      - name: qbittorrentexporter
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 8000
    watchtower: true