# vars/main.yml
docker_role_name: grafana

services:
  - name: grafana
    image: grafana/grafana:latest
    user: "{{ common_uid }}:{{ common_gid }}"
    networks:
      - monitoring
    volumes:
      - ./data/lib:/var/lib/grafana
      - ./data/log:/var/log/grafana
    traefik: 
      - name: grafana
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints.grafana[ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 3000
    watchtower: true