# vars/main.yml
services:
  - name: socks5proxy
    image: serjs/go-socks5-proxy:latest
    env_file:
      - ./socks5proxy.env
    ports:
      - "{{ hostvars[inventory_hostname].ansible_host }}:1080:1080"
    networks:
      - monitoring
    watchtower: true