# vars/main.yml

services:
  - name: sonarr
    image: linuxserver/sonarr:latest
    env_file:
      - ../common.env
    networks:
      - mediaserver
    volumes:
      - ./config:/config
      - /0/merged:/0:rshared
      - /etc/localtime:/etc/localtime:ro
    traefik:
      - name: sonarr
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 8989
    watchtower: true