# /config/workspace/homelab/roles/0host_setup/tasks/mount_nfs
- name: Create mount directory if needed
  file:
    path: "{{ item.mount_point }}"
    state: directory
  loop: "{{ nfs_mounts }}"
  when: nfs_needed|bool

- name: Mount NFS shares
  mount:
    path: "{{ item.mount_point }}"
    src: "{{ item.nfs_server }}:{{ item.nfs_path }}"
    fstype: nfs4
    opts: "{{ item.options }},_netdev"
    state: present
  loop: "{{ nfs_mounts }}"
  when: nfs_needed|bool