- name: Get the list of network interfaces
  find:
    paths: /sys/class/net
    excludes: 'lo,br-*,veth*,docker*,tailscale*,wg*,fake*'
    file_type: any
  register: interfaces

- name: Find the first matching interface
  set_fact:
    interface_name: "{{ item }}"
  loop: "{{ interfaces.files | map(attribute='path') | map('basename') | list }}"
  when: item is match("^en.*|^eth.*")
  loop_control:
    index_var: index
  run_once: "{{ index == 0 }}"

- name: Create netplan configuration
  blockinfile:
    path: "{{ netplan_config }}"
    block: |
      network:
        version: 2
        ethernets:
          eth0:
            match:
              name: "{{ interface_name }}"
            set-name: eth0
    create: yes
  when: interface_name is defined

- name: Apply netplan configuration
  command: netplan apply
  when: interface_name is defined