# vars/main.yml

services:
  - name: urbackupexporter
    image: ghcr.io/ngosang/urbackup-exporter:latest
    env_file:
      - ./urbackupexporter.env
      - ../common.env
    networks:
      - monitoring
    traefik: 
      - name: urbackupexporter
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 9554
    watchtower: true