# vars/main.yml
scripts_path: "/docker/0scripts"
curl_options: "-fsS -m 10 --retry 5 -o /dev/null"
cronjobs:
  photoprism_copy:
    hosts: ['nas']
    minute: "0"
    hour: "8"
    script: "photoprism_copy.sh"
  photoprism_import:
    hosts: ['dmz']
    minute: "0"
    hour: "9"
    script: "photoprism_import.sh"
  pushover_api_test:
    hosts: ['nas']
    minute: "*/15"
    hour: "*"
    script: "pushover_api_test.sh"