# /config/workspace/homelab/playbooks/nas.yml

- hosts: nas
  roles:
    - variables
    # - 0host_user_management
    # - robertdebock.logrotate
    # - name: geerlingguy.security
    #   become: true
    # - geerlingguy.docker
    # - 0docker_setup
    - role: 0docker_service
      vars:
        docker_service_roles:
          - prometheus
          # - rclone # needed for backrest
          # - unifi
          # - uptimekuma
          # - exportarrexporter
          # - pbsexporter
          # - traefik
          # - wallos
          # - paperless
          # - nexterm
          # - changedetection
          # - watchtower
          # # - cronjob
          # - portainer
          # - librespeed
          # - dockge
          # - adguardsync
          # - certdumper
          # - nodeexporter
          # - alertmanager
          # - grafana
          # - cadvisor
          # - proxmoxexporter
          # # - adguardexporter kein bock docker image not found
          # - unifiexporter
          # - plausibleexporter
          # - librespeedexporter
          # - plexexporter
          # - tautulliexporter
          # - qbittorrentexporter
          # - valetudo
          # - pyload
          # - czkawka
          # - pairdrop
          # - backrest

    - role: ansible-proxmox-backup-client
      become: true
      vars:
        proxmox_backup:
          server: "{{ pbs_global_server }}"
          client:
            archives:
              - name: docker2
                path: /docker2
                format: .pxar
              - name: root-home
                path: /root
                format: .pxar
              - name: home
                path: /home
                format: .pxar
            schedule:
                calendar: "*-*-* 16:00:00"
                runifmissed: yes
            encrypt:
              enable: false