# vars/main.yml

services:
  - name: tandoorrecipes-frontend
    image: nginx:mainline-alpine
    depends_on:
      - tandoorrecipes-api
    env_file:
      - ./tandoorrecipes.env
    volumes:
      - ./config:/etc/nginx/conf.d
      - ./data/app:/opt/recipes:ro
    networks:
      - tandoorrecipes
    traefik:
      - name: tandoorrecipes
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 80
      - name: tandoorrecipes_metrics
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`) && PathPrefix(`/metrics`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 80
    watchtower: true

  - name: tandoorrecipes-api
    image: vabene1111/recipes:latest
    depends_on:
      - tandoorrecipes-postgresdb
    env_file:
      - ./tandoorrecipes.env
    volumes:
      - ./config:/opt/recipes/nginx/conf.d
      - ./data/app/staticfiles:/opt/recipes/staticfiles
      - ./data/app/mediafiles:/opt/recipes/mediafiles
    networks:
      - tandoorrecipes
    watchtower: true

  - name: tandoorrecipes-postgresdb
    image: postgres:alpine
    env_file:
      - ./tandoorrecipes-postgres.env
    volumes:
      - ./data/db:/var/lib/postgresql/data
    networks:
      - tandoorrecipes
    watchtower: true
