# vars/main.yml

services:
  - name: prowlarr
    image: hotio/prowlarr:latest
    env_file:
      - ../common.env
    networks:
      - mediaserver
    volumes:
      - ./config:/config
    traefik:
      - name: prowlarr
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-oauth-chain@file
        insecuretransport: false
        service_port: 9696
    watchtower: true