# /config/workspace/homelab/playbooks/nas.yml

- hosts: nas
  roles:
    - variables
    # - 0host_user_management
    # - robertdebock.logrotate
    # - name: geerlingguy.security
      # become: true
    # - geerlingguy.docker
    - 0docker_setup
    - role: 0docker_service
      vars:
        docker_service_roles:
          - traefik
          - watchtower
          # - cronjob
          - portainer
          - unifi
          - librespeed
          - dockge
          - adguardsync
          - prometheus
          - certdumper
          - nodeexporter
          - alertmanager
          - grafana