# traefik_playbook.yml
- hosts: docker
  tasks:
    - name: Generate Docker Compose file
      template:
        src: ../templates/traefik.j2
        dest: /docker2/traefik/docker-compose.yml

    - name: Create Docker Networks
      docker_network:
        name: "{{ item }}"
        ipam_config:
          - subnet: "172.29.{{ loop.index }}.0/24"
      loop: "{{ additional_networks }}"
      loop_control:
        index_var: loop

