# vars/main.yml
services:
  - name: pyload
    image: lscr.io/linuxserver/pyload-ng:latest
    env_file:
      - ../common.env
    volumes:
      - ./data:/config
      - /srv/dev-disk-by-uuid-4cf2cd9e-0885-47b9-ada6-6005c3daa474/Multimedia/Downloads:/downloads
    networks:
      - pyload
    traefik: 
      - name: pyload
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 8000
    watchtower: true