---
- name: Configure Host for HTTP3
  become: true
  block:
    - name: Set net.core.rmem_max
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: 'net.core.rmem_max=2500000'
        create: yes

    - name: Set net.core.wmem_max
      ansible.builtin.lineinfile:
        path: /etc/sysctl.conf
        line: 'net.core.wmem_max=2500000'
        create: yes

    - name: Reload sysctl
      ansible.builtin.command:
        cmd: sysctl -p
      become: true
