# vars/main.yml

services:
  - name: tautulli
    image: linuxserver/tautulli:latest
    env_file:
      - ../common.env
    networks:
      - mediaserver
    volumes:
      - ./config:/config
    traefik:
      - name: tautulli
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: false
        service_port: 8181
    watchtower: true