# vars/main.yml

services:
  - name: actualbudget
    image: docker.io/actualbudget/actual-server:latest
    env_file:
      - ./actualbudget.env
    volumes:
      - ./data:/data
    networks:
      - actualbudget
    traefik:
      - name: actualbudget
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-oauth-chain@file
        insecuretransport: false
        service_port: 5006
    watchtower: true

  - name: actual-ai
    image: docker.io/sakowicz/actual-ai:latest
    depends_on:
      - actualbudget
      - azure-proxy
    env_file:
      - ./actual-ai.env
    networks:
      - actualbudget
    watchtower: true

  - name: azure-proxy
    image: stulzq/azure-openai-proxy:latest
    env_file:
      - ./azure-proxy.env
    networks:
      - actualbudget
    watchtower: true