# vars/main.yml

services:
  - name: cloudplow
    image: ghcr.io/sabrsorensen/alpine-cloudplow:latest
    network_mode: host
    env_file:
      - ../common.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /0/local:/data
      - ./config:/config
      - ../rclone/config/:/rclone
    watchtower: true