# vars/main.yml

services:
  - name: gpt-researcher
    image: gptresearcher/gpt-researcher:latest
    user: "{{ common_uid }}:{{ common_gid }}"
    env_file:
      - ./gpt-researcher.env
    volumes:
      - ./data/my-docs:/usr/src/app/my-docs
      - ./data/outputs:/usr/src/app/outputs
      - ./data/logs:/usr/src/app/logs
    networks:
      - gpt-researcher
    traefik:
      - name: gpt-researcher-api
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']][0] }}`)"
        middlewares: public-oauth-chain@file
        insecuretransport: false
        service_port: 8000
    watchtower: true

  - name: gpt-researcher-mcp
    image: codeligence/gptr-mcp:latest
    env_file:
      - ./gpt-researcher.env
    networks:
      - librechat
    watchtower: true


  - name: gpt-researcher-nextjs
    image: gptresearcher/gptr-nextjs:latest
    depends_on:
      - gpt-researcher
    env_file:
      - ./gpt-researcher-nextjs.env
    volumes:
      - ./data/outputs:/app/outputs
    networks:
      - gpt-researcher
    traefik:
      - name: gpt-researcher
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']][1] }}`)"
        middlewares: public-oauth-chain@file
        insecuretransport: false
        service_port: 3000
    watchtower: true