# - name: Add backup directories
#   command: >
#     {{ urbackup_client_install_dir }}/urbackupclientctl add-backupdir --path {{ item }}
#   with_items: "{{ backup_dirs }}"
#   become: true

- name: Set server address
  command: >
    {{ urbackup_client_install_dir }}/urbackupclientctl set-settings --server-url {{ urbackup_server_address }}
  become: true

# - name: Set client authkey
#   command: >
#     {{ urbackup_client_install_dir }}/urbackupclientctl set-settings --authkey {{ urbackup_client_authkey }}
#   become: true

- name: Set Client Name
  command: >
    {{ urbackup_client_install_dir }}/urbackupclientctl set-settings --name {{ urbackup_client_name }}
  become: true