- name: Install dependencies
  apt:
    name: 
      - wget
    state: present
    update_cache: yes
  become: true

- name: Add Datto GPG key
  shell: sudo apt-key adv --fetch-keys https://cpkg.datto.com/DATTO-PKGS-GPG-KEY
  args:
    executable: /bin/bash

- name: Add Datto repository
  shell: echo "deb [arch=amd64] https://cpkg.datto.com/datto-deb/public/$(lsb_release -sc) $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/datto-linux-agent.list
  args:
    executable: /bin/bash

- name: Update package cache
  apt:
    update_cache: yes
  become: true

- name: Install Datto packages
  apt:
    name: 
      - dattobd-dkms
      - dattobd-utils
    state: present
  become: true

- name: Download and install UrBackup client
  shell: |
    TF=$(mktemp) && wget "{{ urbackup_client_url }}" -O $TF && DATTO=yes sudo sh $TF && rm -f $TF
  args:
    executable: /bin/bash
  become: true

