# vars/main.yml

services:
  - name: overseerr
    image: lscr.io/linuxserver/overseerr:latest
    env_file:
      - ../common.env
    networks:
      - mediaserver
    volumes:
      - ./config:/config
    traefik:
      - name: overseerr
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: public-chain@file
        insecuretransport: false
        service_port: 5055
    watchtower: true