# vars/main.yml

services:
  - name: unifi
    image: lscr.io/linuxserver/unifi-network-application:latest
    depends_on:
      - unifi-mongodb
    env_file:
      - ./unifi.env
      - ../common.env
    networks:
      - unifi
    volumes:
      - ./data:/config
    traefik: 
      - name: unifi
        protocol: http
        entrypoint: https
        http_redirection: true
        enable_tls: true
        rule: "Host(`{{ endpoints[role_specific][ansible_facts['hostname']] }}`)"
        middlewares: private-chain@file
        insecuretransport: true
        service_port: 8443
      - name: unifi-1900
        protocol: udp
        entrypoint: unifi
        http_redirection: false
        enable_tls: false
        insecuretransport: false
        service_port: 1900
      - name: unifi-3478
        protocol: udp
        entrypoint: unifi2
        http_redirection: false
        enable_tls: false
        insecuretransport: false
        service_port: 3478
      - name: unifi-5514
        protocol: udp
        entrypoint: unifi3
        http_redirection: false
        enable_tls: false
        insecuretransport: false
        service_port: 5514
      - name: unifi-6789
        protocol: tcp
        entrypoint: unifi4
        http_redirection: false
        enable_tls: false
        rule: HostSNI(`*`)
        insecuretransport: false
        service_port: 6789
      - name: unifi-8080
        protocol: tcp
        entrypoint: unifi5
        http_redirection: false
        enable_tls: false
        rule: HostSNI(`*`)
        insecuretransport: false
        service_port: 8080
      - name: unifi-8843
        protocol: tcp
        entrypoint: unifi6
        http_redirection: false
        enable_tls: false
        rule: HostSNI(`*`)
        insecuretransport: false
        service_port: 8843
      - name: unifi-8880
        protocol: tcp
        entrypoint: unifi7
        http_redirection: false
        enable_tls: false
        rule: HostSNI(`*`)
        insecuretransport: false
        service_port: 8880
      - name: unifi-10001
        protocol: udp
        entrypoint: unifi8
        http_redirection: false
        enable_tls: false
        insecuretransport: false
        service_port: 10001
    watchtower: true

  - name: unifi-mongodb
    image: mongo:latest
    networks:
      - unifi
    volumes:
      - ./db/db:/data/db # both needed like this
      - ./db/configdb:/data/configdb # both needed like this
      - ./config/unifi_mongodb_init.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    watchtower: true
    uptimekuma_container_monitor: true